version: '3.9'

services:
  get_the_flaaaaaaaaaa:
    restart: always
    build:
      context: "./challenges/pwn/get_the_flaAAAAAAAAA"
      dockerfile: "./Dockerfile"
    ports: 
      - "50371:1337"
  web-servercheck:
    restart: always
    build:
      context: "./challenges/web/servercheck"
      dockerfile: "./Dockerfile"
    ports:
      - "25870:8080"
  misc-catz:
    restart: always
    build:
      context: "./challenges/misc/catz"
      dockerfile: "./Dockerfile"
    ports:
      - "36416:1337"
  misc-calc:
    restart: always
    build:
      context: "./challenges/misc/calc"
      dockerfile: "./Dockerfile"
    ports:
      - "15867:1337"
  web-animal-farm:
    restart: always
    build:
      context: "./challenges/web/animal-farm"
      dockerfile: "./Dockerfile"
    ports:
      - "63122:8000"
  helpers-web-bot:
    restart: always
    build:
      context: "./helpers/web-bot"
      dockerfile: "./Dockerfile"
    ports:
      - "15341:5000"
  web-hacker-name-generator:
    restart: always
    build:
      context: "./challenges/web/hacker-name-generator"
      dockerfile: "./Dockerfile"
    ports:
      - "34554:8000"
