version: '3.9'

services:
  get_the_flaaaaaaaaaa:
    restart: always
    build:
      context: "./challenges/pwn/get_the_flaAAAAAAAAA"
      dockerfile: "./Dockerfile"
    ports: 
      - "50371:1337"
  web-servercheck:
    restart: always
    build:
      context: "./challenges/web/servercheck"
      dockerfile: "./Dockerfile"
    ports:
      - "25870:8080"
  misc-catz:
    restart: always
    build:
      context: "./challenges/misc/catz"
      dockerfile: "./Dockerfile"
    ports:
      - "36416:1337"
